
[paths]
output_dir = "output"
#
#
# trajectory_dir = "/home/timo/Media/Documents/tutkimus/Gälve_Nevia/Dataset/Alakylantie/project/Slam_Project/useful/20260709-223709_Rtk.dfnav"
laz_dir = "datasets/HaVa_Paikkatietoaineisto_EPSG_3067/250417_Hava_E18_Record062_250417_140207_Scanner_1.laz"
trajectory_dir = "datasets//HaVa_Paikkatietoaineisto_EPSG_3067/Trajectory - 250417_140207_Scanner_1.txt"
#


datasetroot = "datasets/generated"
coco_file = "datasets/_annotations.coco.json"

[image]
# Optional: if omitted, defaults will be used
max_range = 50
elevation_range  = [-45 ,45]
width= 1024
height= 128



[sensor]
# Optional: if omitted, defaults will be used
sensor_orientation = [0.0, 0.0, 0.0]
use_trajectory_orientation = true

[processing]

fields=['intensity', 'classification', 'id']

pipeline = 'coco, detected'
number_of_processes = 4
sampling_points = 1000

skip_start = 0 # trajectory points to be skipped from the start
skip_end = 0   # trajectory points to be skipped from the end
stride_distance = 10 #step size in meters

randomize = true
pos_pertubations = 0
orientaton_pertubations = 0
rand_range_x = [-5,5]
rand_range_y = [-5,5]
rand_range_z = [0.5,1.5]

rand_range_roll = [-10,10]
rand_range_pitch = [-15,15]
rand_range_yaw = [-180,180]

x_segment  = [0.05,0.95]
y_segment = [0.05,0.95]
z_segment = [0.0,0.5]

classes = [0,1,2]


[pole_detection]

cell_size = 5.5
z_percentile = 50
clearance_m = 0.20

fill_holes = false
eps_xy = 1.0
min_samples = 25
r_max_m = 0.5
verticality_min = 0.85
stride_distance = 30 #step size in meters
h_min = 1.3
local_area_distance = 60
